version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ai-tutor-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-in-production}
      - DATABASE_URL=sqlite:///./knowledge_tutor.db
      - MAX_FILE_SIZE=10485760
    volumes:
      - uploads_data:/app/uploads
      - db_data:/app
    networks:
      - ai-tutor-network

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
    container_name: ai-tutor-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ai-tutor-network

networks:
  ai-tutor-network:
    driver: bridge

volumes:
  uploads_data:
  db_data:
