name: Deploy to Hetzner

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Navigate to project directory
            cd /var/www/ai-knowledge-tutor || mkdir -p /var/www/ai-knowledge-tutor && cd /var/www/ai-knowledge-tutor

            # Pull latest code
            if [ -d ".git" ]; then
              git pull origin master
            else
              git clone https://github.com/${{ github.repository }} .
            fi

            # Create .env file if not exists
            if [ ! -f ".env" ]; then
              echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
              echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
              echo "REACT_APP_API_URL=https://tutor.marcchesnel.com" >> .env
            fi

            # Stop existing containers
            docker-compose down || true

            # Build and start containers
            docker-compose up -d --build

            # Clean up old images
            docker image prune -f

      - name: Setup nginx config (first time only)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Copy nginx config if not exists
            if [ ! -f "/etc/nginx/sites-available/tutor.marcchesnel.com" ]; then
              cp /var/www/ai-knowledge-tutor/deployment/nginx-tutor.marcchesnel.com /etc/nginx/sites-available/tutor.marcchesnel.com
              ln -sf /etc/nginx/sites-available/tutor.marcchesnel.com /etc/nginx/sites-enabled/

              # Get SSL certificate
              certbot --nginx -d tutor.marcchesnel.com --non-interactive --agree-tos --email marc@marcchesnel.com

              # Reload nginx
              nginx -t && systemctl reload nginx
            fi
